spring:
  application:
    name: RomashkaKo

  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin123
    url: jdbc:postgresql://localhost:5432/romashka-ko_db

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: /db/changelog/master-db.yaml

  config:
    import: classpath:cache-config.yaml

logging:
  level:
    org.springframework.cache: TRACE
    org.springframework.cache.interceptor: TRACE
    org.springframework.data.redis: TRACE