spring:
  application:
  name: RomashkaKo

  datasource:
    url: jdbc:postgresql://localhost:5432/romashka-ko_db
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  liquibase:
    enabled: true

